In [1]:
import numpy as np
import os

DIR = "/home/swl/Mask_RCNN/mask/"

In [2]:
list = os.listdir(DIR)
# print(list)

for original_name in list:
    dir = os.path.join(DIR,original_name)
    root, ext = os.path.splitext(original_name)
    
    arr = np.load(dir)
    
#     new_arr = np.rot90(arr)
# #     new_name = root + "__flipv" + ext
#     new_name = root + "__rot90" + ext
#     np.save(new_name, new_arr)
    
#     new_arr = np.rot90(new_arr)
#     new_name = root + "__rot180" + ext
#     np.save(new_name, new_arr)
    
#     new_arr = np.rot90(new_arr)
#     new_name = root + "__rot270" + ext
    np.save(new_name, new_arr)
    


KeyboardInterrupt: 

In [3]:
a = np.array([[1, 1, 0],[1, 0, 0],[1, 0, 0]])

print(a)
print(np.fliplr(a))
print(np.flipud(a))
a = np.rot90(a)
print(a)
a = np.rot90(a)
print(a)
a = np.rot90(a)
print(a)

[[1 1 0]
 [1 0 0]
 [1 0 0]]
[[0 1 1]
 [0 0 1]
 [0 0 1]]
[[1 0 0]
 [1 0 0]
 [1 1 0]]
[[0 0 0]
 [1 0 0]
 [1 1 1]]
[[0 0 1]
 [0 0 1]
 [0 1 1]]
[[1 1 1]
 [0 0 1]
 [0 0 0]]
