In [9]:
import numpy as np
import os

DIR = "/home/swl/Mask_RCNN/mask/"

In [10]:
list = os.listdir(DIR)
# print(list)

for original_name in list:
    dir = os.path.join(DIR,original_name)
    arr = np.load(dir)
    new_arr = np.flipud(arr)
    root, ext = os.path.splitext(original_name)
    new_name = root + "__flipv" + ext
#     new_name = root + "__rot90" + ext
#     print(new_name)
    np.save(new_name, new_arr)
    


In [11]:
a = np.array([[1, 1, 0],[1, 0, 0],[1, 0, 0]])

print(a)
print(np.fliplr(a))
print(np.flipud(a))
a = np.rot90(a)
print(a)
a = np.rot90(a)
print(a)
a = np.rot90(a)
print(a)

[[1 1 0]
 [1 0 0]
 [1 0 0]]
[[0 1 1]
 [0 0 1]
 [0 0 1]]
[[1 0 0]
 [1 0 0]
 [1 1 0]]
[[0 0 0]
 [1 0 0]
 [1 1 1]]
[[0 0 1]
 [0 0 1]
 [0 1 1]]
[[1 1 1]
 [0 0 1]
 [0 0 0]]
